### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by EbrahimiAmirHosein** [FrancisLawlor/MIPS32BinarySearch#1]
is it recursive ?

**Comment by FrancisLawlor** [comment]
The logic in this code is identical to what is implemented here in Java: https://gist.github.com/FrancisLawlor/b9da432a35a49a0c375b8470df9e2629

In this MIPS32 implementation, rather than return -1, we store the value 0 in the register to indicate the absence of the target value. And as you can see from the gist, no recursion is involved.
